// Generated by gencpp from file aqua_gait/UpdateTargetRPYDResponse.msg
// DO NOT EDIT!


#ifndef AQUA_GAIT_MESSAGE_UPDATETARGETRPYDRESPONSE_H
#define AQUA_GAIT_MESSAGE_UPDATETARGETRPYDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aqua_gait
{
template <class ContainerAllocator>
struct UpdateTargetRPYDResponse_
{
  typedef UpdateTargetRPYDResponse_<ContainerAllocator> Type;

  UpdateTargetRPYDResponse_()
    {
    }
  UpdateTargetRPYDResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }






  typedef boost::shared_ptr< ::aqua_gait::UpdateTargetRPYDResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aqua_gait::UpdateTargetRPYDResponse_<ContainerAllocator> const> ConstPtr;

}; // struct UpdateTargetRPYDResponse_

typedef ::aqua_gait::UpdateTargetRPYDResponse_<std::allocator<void> > UpdateTargetRPYDResponse;

typedef boost::shared_ptr< ::aqua_gait::UpdateTargetRPYDResponse > UpdateTargetRPYDResponsePtr;
typedef boost::shared_ptr< ::aqua_gait::UpdateTargetRPYDResponse const> UpdateTargetRPYDResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aqua_gait::UpdateTargetRPYDResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aqua_gait::UpdateTargetRPYDResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace aqua_gait

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::aqua_gait::UpdateTargetRPYDResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aqua_gait::UpdateTargetRPYDResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aqua_gait::UpdateTargetRPYDResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aqua_gait::UpdateTargetRPYDResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aqua_gait::UpdateTargetRPYDResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aqua_gait::UpdateTargetRPYDResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aqua_gait::UpdateTargetRPYDResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::aqua_gait::UpdateTargetRPYDResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::aqua_gait::UpdateTargetRPYDResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aqua_gait/UpdateTargetRPYDResponse";
  }

  static const char* value(const ::aqua_gait::UpdateTargetRPYDResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aqua_gait::UpdateTargetRPYDResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
\n\
";
  }

  static const char* value(const ::aqua_gait::UpdateTargetRPYDResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aqua_gait::UpdateTargetRPYDResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UpdateTargetRPYDResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aqua_gait::UpdateTargetRPYDResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::aqua_gait::UpdateTargetRPYDResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // AQUA_GAIT_MESSAGE_UPDATETARGETRPYDRESPONSE_H
