(cl:in-package aquajoy-msg)
(cl:export '(JOY_AXIS_DEADZONE-VAL
          JOY_AXIS_DEADZONE
          MAX_SPEED_CMD-VAL
          MAX_SPEED_CMD
          MAX_HEAVE_CMD-VAL
          MAX_HEAVE_CMD
          MAX_ROLL_CMD-VAL
          MAX_ROLL_CMD
          MAX_PITCH_CMD-VAL
          MAX_PITCH_CMD
          MAX_YAW_CMD-VAL
          MAX_YAW_CMD
          MAX_ROLL_POS-VAL
          MAX_ROLL_POS
          MAX_PITCH_POS-VAL
          MAX_PITCH_POS
          MAX_YAW_POS-VAL
          MAX_YAW_POS
          MIN_DEPTH-VAL
          MIN_DEPTH
          MAX_DEPTH-VAL
          MAX_DEPTH
          DEFAULT_FIXED_DEPTH-VAL
          DEFAULT_FIXED_DEPTH
          MAX_ROLL_VEL-VAL
          MAX_ROLL_VEL
          MAX_PITCH_VEL-VAL
          MAX_PITCH_VEL
          MAX_YAW_VEL-VAL
          MAX_YAW_VEL
          MAX_DEPTH_VEL-VAL
          MAX_DEPTH_VEL
))