(cl:in-package aquacore-msg)
(cl:export '(HEADER-VAL
          HEADER
          LED-VAL
          LED
          GAIT-VAL
          GAIT
          ROLLANGLE-VAL
          ROLLANGLE
          PITCHANGLE-VAL
          PITCHANGLE
          YAWANGLE-VAL
          YAWANGLE
          ROLLTARGETANGLE-VAL
          ROLLTARGETANGLE
          PITCHTARGETANGLE-VAL
          PITCHTARGETANGLE
          YAWTARGETANGLE-VAL
          YAWTARGETANGLE
          DEPTHTARGET-VAL
          DEPTHTARGET
          AVGROLLCOMMAND-VAL
          AVGROLLCOMMAND
          AVGPITCHCOMMAND-VAL
          AVGPITCHCOMMAND
          AVGYAWCOMMAND-VAL
          AVGYAWCOMMAND
          AVGHEAVECOMMAND-VAL
          AVGHEAVECOMMAND
          AVGSURGECOMMAND-VAL
          AVGSURGECOMMAND
          AUTOPILOTMODE-VAL
          AUTOPILOTMODE
          DEPTH-VAL
          DEPTH
          SPEED-VAL
          SPEED
          LEGCURRENTS-VAL
          LEGCURRENTS
))