(cl:defpackage aquajoy-srv
  (:use )
  (:export
   "UPDATEAQUATELEOPJOYPARAMS"
   "<UPDATEAQUATELEOPJOYPARAMS-REQUEST>"
   "UPDATEAQUATELEOPJOYPARAMS-REQUEST"
   "<UPDATEAQUATELEOPJOYPARAMS-RESPONSE>"
   "UPDATEAQUATELEOPJOYPARAMS-RESPONSE"
  ))

