(cl:defpackage aqua_gazebo-msg
  (:use )
  (:export
   "<HYDRODYNAMICSPARAMS>"
   "HYDRODYNAMICSPARAMS"
   "<HYDRODYNAMICSPARAMS>"
   "HYDRODYNAMICSPARAMS"
   "<HYDRODYNAMICSPARAMSLIST>"
   "HYDRODYNAMICSPARAMSLIST"
   "<HYDRODYNAMICSPARAMSLIST>"
   "HYDRODYNAMICSPARAMSLIST"
   "<THRUSTPARAMS>"
   "THRUSTPARAMS"
   "<THRUSTPARAMS>"
   "THRUSTPARAMS"
  ))

