(cl:in-package aqua_gazebo-msg)
(cl:export '(HEADER-VAL
          HEADER
          NAME-VAL
          NAME
          WOBBLE-VAL
          WOBBLE
          DRAG_SCALING-VAL
          DRAG_SCALING
          DENSITY-VAL
          DENSITY
          VISCOSITY-VAL
          VISCOSITY
          MASS-VAL
          MASS
          VOLUME-VAL
          VOLUME
          PLANAR-VAL
          PLANAR
          K-VAL
          K
          D-VAL
          D
          I-VAL
          I
          COM-VAL
          COM
          COB-VAL
          COB
))