// Generated by gencpp from file aquajoy/UpdateAquaTeleopJoyParamsResponse.msg
// DO NOT EDIT!


#ifndef AQUAJOY_MESSAGE_UPDATEAQUATELEOPJOYPARAMSRESPONSE_H
#define AQUAJOY_MESSAGE_UPDATEAQUATELEOPJOYPARAMSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aquajoy
{
template <class ContainerAllocator>
struct UpdateAquaTeleopJoyParamsResponse_
{
  typedef UpdateAquaTeleopJoyParamsResponse_<ContainerAllocator> Type;

  UpdateAquaTeleopJoyParamsResponse_()
    {
    }
  UpdateAquaTeleopJoyParamsResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }






  typedef boost::shared_ptr< ::aquajoy::UpdateAquaTeleopJoyParamsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aquajoy::UpdateAquaTeleopJoyParamsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct UpdateAquaTeleopJoyParamsResponse_

typedef ::aquajoy::UpdateAquaTeleopJoyParamsResponse_<std::allocator<void> > UpdateAquaTeleopJoyParamsResponse;

typedef boost::shared_ptr< ::aquajoy::UpdateAquaTeleopJoyParamsResponse > UpdateAquaTeleopJoyParamsResponsePtr;
typedef boost::shared_ptr< ::aquajoy::UpdateAquaTeleopJoyParamsResponse const> UpdateAquaTeleopJoyParamsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aquajoy::UpdateAquaTeleopJoyParamsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aquajoy::UpdateAquaTeleopJoyParamsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace aquajoy

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'aquajoy': ['/home/ran/Documents/Assignment1/src/aquajoy/msg'], 'aquacore': ['/home/ran/Documents/Assignment1/src/aquacore/msg', '/home/ran/Documents/Assignment1/devel/share/aquacore/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::aquajoy::UpdateAquaTeleopJoyParamsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aquajoy::UpdateAquaTeleopJoyParamsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aquajoy::UpdateAquaTeleopJoyParamsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aquajoy::UpdateAquaTeleopJoyParamsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aquajoy::UpdateAquaTeleopJoyParamsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aquajoy::UpdateAquaTeleopJoyParamsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aquajoy::UpdateAquaTeleopJoyParamsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::aquajoy::UpdateAquaTeleopJoyParamsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::aquajoy::UpdateAquaTeleopJoyParamsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aquajoy/UpdateAquaTeleopJoyParamsResponse";
  }

  static const char* value(const ::aquajoy::UpdateAquaTeleopJoyParamsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aquajoy::UpdateAquaTeleopJoyParamsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
";
  }

  static const char* value(const ::aquajoy::UpdateAquaTeleopJoyParamsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aquajoy::UpdateAquaTeleopJoyParamsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UpdateAquaTeleopJoyParamsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aquajoy::UpdateAquaTeleopJoyParamsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::aquajoy::UpdateAquaTeleopJoyParamsResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // AQUAJOY_MESSAGE_UPDATEAQUATELEOPJOYPARAMSRESPONSE_H
