// Generated by gencpp from file aquacore/GetAutopilotStateResponse.msg
// DO NOT EDIT!


#ifndef AQUACORE_MESSAGE_GETAUTOPILOTSTATERESPONSE_H
#define AQUACORE_MESSAGE_GETAUTOPILOTSTATERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aquacore
{
template <class ContainerAllocator>
struct GetAutopilotStateResponse_
{
  typedef GetAutopilotStateResponse_<ContainerAllocator> Type;

  GetAutopilotStateResponse_()
    : ap_state(0)
    , ap_mode(0)
    , params()
    , target_depth(0.0)
    , target_roll(0.0)
    , target_pitch(0.0)
    , target_yaw(0.0)  {
    }
  GetAutopilotStateResponse_(const ContainerAllocator& _alloc)
    : ap_state(0)
    , ap_mode(0)
    , params(_alloc)
    , target_depth(0.0)
    , target_roll(0.0)
    , target_pitch(0.0)
    , target_yaw(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _ap_state_type;
  _ap_state_type ap_state;

   typedef int32_t _ap_mode_type;
  _ap_mode_type ap_mode;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _params_type;
  _params_type params;

   typedef float _target_depth_type;
  _target_depth_type target_depth;

   typedef float _target_roll_type;
  _target_roll_type target_roll;

   typedef float _target_pitch_type;
  _target_pitch_type target_pitch;

   typedef float _target_yaw_type;
  _target_yaw_type target_yaw;




  typedef boost::shared_ptr< ::aquacore::GetAutopilotStateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aquacore::GetAutopilotStateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetAutopilotStateResponse_

typedef ::aquacore::GetAutopilotStateResponse_<std::allocator<void> > GetAutopilotStateResponse;

typedef boost::shared_ptr< ::aquacore::GetAutopilotStateResponse > GetAutopilotStateResponsePtr;
typedef boost::shared_ptr< ::aquacore::GetAutopilotStateResponse const> GetAutopilotStateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aquacore::GetAutopilotStateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aquacore::GetAutopilotStateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace aquacore

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'aquacore': ['/home/ran/Documents/Assignment1/src/aquacore/msg', '/home/ran/Documents/Assignment1/devel/share/aquacore/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::aquacore::GetAutopilotStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aquacore::GetAutopilotStateResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aquacore::GetAutopilotStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aquacore::GetAutopilotStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aquacore::GetAutopilotStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aquacore::GetAutopilotStateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aquacore::GetAutopilotStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8c8eeaafe647710bb35d5cfef6b22f76";
  }

  static const char* value(const ::aquacore::GetAutopilotStateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8c8eeaafe647710bULL;
  static const uint64_t static_value2 = 0xb35d5cfef6b22f76ULL;
};

template<class ContainerAllocator>
struct DataType< ::aquacore::GetAutopilotStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aquacore/GetAutopilotStateResponse";
  }

  static const char* value(const ::aquacore::GetAutopilotStateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aquacore::GetAutopilotStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32	   ap_state\n\
int32	   ap_mode\n\
float32[] params\n\
float32    target_depth\n\
float32    target_roll\n\
float32    target_pitch\n\
float32    target_yaw\n\
";
  }

  static const char* value(const ::aquacore::GetAutopilotStateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aquacore::GetAutopilotStateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ap_state);
      stream.next(m.ap_mode);
      stream.next(m.params);
      stream.next(m.target_depth);
      stream.next(m.target_roll);
      stream.next(m.target_pitch);
      stream.next(m.target_yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetAutopilotStateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aquacore::GetAutopilotStateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aquacore::GetAutopilotStateResponse_<ContainerAllocator>& v)
  {
    s << indent << "ap_state: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ap_state);
    s << indent << "ap_mode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ap_mode);
    s << indent << "params[]" << std::endl;
    for (size_t i = 0; i < v.params.size(); ++i)
    {
      s << indent << "  params[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.params[i]);
    }
    s << indent << "target_depth: ";
    Printer<float>::stream(s, indent + "  ", v.target_depth);
    s << indent << "target_roll: ";
    Printer<float>::stream(s, indent + "  ", v.target_roll);
    s << indent << "target_pitch: ";
    Printer<float>::stream(s, indent + "  ", v.target_pitch);
    s << indent << "target_yaw: ";
    Printer<float>::stream(s, indent + "  ", v.target_yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AQUACORE_MESSAGE_GETAUTOPILOTSTATERESPONSE_H
