// Generated by gencpp from file aquacore/GetAutopilotParamsResponse.msg
// DO NOT EDIT!


#ifndef AQUACORE_MESSAGE_GETAUTOPILOTPARAMSRESPONSE_H
#define AQUACORE_MESSAGE_GETAUTOPILOTPARAMSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aquacore
{
template <class ContainerAllocator>
struct GetAutopilotParamsResponse_
{
  typedef GetAutopilotParamsResponse_<ContainerAllocator> Type;

  GetAutopilotParamsResponse_()
    : params()  {
    }
  GetAutopilotParamsResponse_(const ContainerAllocator& _alloc)
    : params(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _params_type;
  _params_type params;




  typedef boost::shared_ptr< ::aquacore::GetAutopilotParamsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aquacore::GetAutopilotParamsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetAutopilotParamsResponse_

typedef ::aquacore::GetAutopilotParamsResponse_<std::allocator<void> > GetAutopilotParamsResponse;

typedef boost::shared_ptr< ::aquacore::GetAutopilotParamsResponse > GetAutopilotParamsResponsePtr;
typedef boost::shared_ptr< ::aquacore::GetAutopilotParamsResponse const> GetAutopilotParamsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aquacore::GetAutopilotParamsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aquacore::GetAutopilotParamsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace aquacore

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'aquacore': ['/home/ran/Documents/Assignment1/src/aquacore/msg', '/home/ran/Documents/Assignment1/devel/share/aquacore/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::aquacore::GetAutopilotParamsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aquacore::GetAutopilotParamsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aquacore::GetAutopilotParamsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aquacore::GetAutopilotParamsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aquacore::GetAutopilotParamsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aquacore::GetAutopilotParamsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aquacore::GetAutopilotParamsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8e22f8c3368a715022fd214d9775704d";
  }

  static const char* value(const ::aquacore::GetAutopilotParamsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8e22f8c3368a7150ULL;
  static const uint64_t static_value2 = 0x22fd214d9775704dULL;
};

template<class ContainerAllocator>
struct DataType< ::aquacore::GetAutopilotParamsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aquacore/GetAutopilotParamsResponse";
  }

  static const char* value(const ::aquacore::GetAutopilotParamsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aquacore::GetAutopilotParamsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] params\n\
\n\
";
  }

  static const char* value(const ::aquacore::GetAutopilotParamsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aquacore::GetAutopilotParamsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.params);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetAutopilotParamsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aquacore::GetAutopilotParamsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aquacore::GetAutopilotParamsResponse_<ContainerAllocator>& v)
  {
    s << indent << "params[]" << std::endl;
    for (size_t i = 0; i < v.params.size(); ++i)
    {
      s << indent << "  params[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.params[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AQUACORE_MESSAGE_GETAUTOPILOTPARAMSRESPONSE_H
