// Generated by gencpp from file aquacore/MenuResponse.msg
// DO NOT EDIT!


#ifndef AQUACORE_MESSAGE_MENURESPONSE_H
#define AQUACORE_MESSAGE_MENURESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aquacore
{
template <class ContainerAllocator>
struct MenuResponse_
{
  typedef MenuResponse_<ContainerAllocator> Type;

  MenuResponse_()
    : selection(0)  {
    }
  MenuResponse_(const ContainerAllocator& _alloc)
    : selection(0)  {
  (void)_alloc;
    }



   typedef int32_t _selection_type;
  _selection_type selection;




  typedef boost::shared_ptr< ::aquacore::MenuResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aquacore::MenuResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MenuResponse_

typedef ::aquacore::MenuResponse_<std::allocator<void> > MenuResponse;

typedef boost::shared_ptr< ::aquacore::MenuResponse > MenuResponsePtr;
typedef boost::shared_ptr< ::aquacore::MenuResponse const> MenuResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aquacore::MenuResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aquacore::MenuResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace aquacore

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'aquacore': ['/home/ran/Documents/Assignment1/src/aquacore/msg', '/home/ran/Documents/Assignment1/devel/share/aquacore/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::aquacore::MenuResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aquacore::MenuResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aquacore::MenuResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aquacore::MenuResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aquacore::MenuResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aquacore::MenuResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aquacore::MenuResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dfce931559b01752ff575a8c4cbe9bc4";
  }

  static const char* value(const ::aquacore::MenuResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdfce931559b01752ULL;
  static const uint64_t static_value2 = 0xff575a8c4cbe9bc4ULL;
};

template<class ContainerAllocator>
struct DataType< ::aquacore::MenuResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aquacore/MenuResponse";
  }

  static const char* value(const ::aquacore::MenuResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aquacore::MenuResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 selection\n\
\n\
\n\
";
  }

  static const char* value(const ::aquacore::MenuResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aquacore::MenuResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.selection);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MenuResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aquacore::MenuResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aquacore::MenuResponse_<ContainerAllocator>& v)
  {
    s << indent << "selection: ";
    Printer<int32_t>::stream(s, indent + "  ", v.selection);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AQUACORE_MESSAGE_MENURESPONSE_H
