// Generated by gencpp from file aquacore/RunSimulationUntilTimeRequest.msg
// DO NOT EDIT!


#ifndef AQUACORE_MESSAGE_RUNSIMULATIONUNTILTIMEREQUEST_H
#define AQUACORE_MESSAGE_RUNSIMULATIONUNTILTIMEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aquacore
{
template <class ContainerAllocator>
struct RunSimulationUntilTimeRequest_
{
  typedef RunSimulationUntilTimeRequest_<ContainerAllocator> Type;

  RunSimulationUntilTimeRequest_()
    : desired_time()  {
    }
  RunSimulationUntilTimeRequest_(const ContainerAllocator& _alloc)
    : desired_time()  {
  (void)_alloc;
    }



   typedef ros::Time _desired_time_type;
  _desired_time_type desired_time;




  typedef boost::shared_ptr< ::aquacore::RunSimulationUntilTimeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aquacore::RunSimulationUntilTimeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RunSimulationUntilTimeRequest_

typedef ::aquacore::RunSimulationUntilTimeRequest_<std::allocator<void> > RunSimulationUntilTimeRequest;

typedef boost::shared_ptr< ::aquacore::RunSimulationUntilTimeRequest > RunSimulationUntilTimeRequestPtr;
typedef boost::shared_ptr< ::aquacore::RunSimulationUntilTimeRequest const> RunSimulationUntilTimeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aquacore::RunSimulationUntilTimeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aquacore::RunSimulationUntilTimeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace aquacore

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'aquacore': ['/home/ran/Documents/Assignment1/src/aquacore/msg', '/home/ran/Documents/Assignment1/devel/share/aquacore/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::aquacore::RunSimulationUntilTimeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aquacore::RunSimulationUntilTimeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aquacore::RunSimulationUntilTimeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aquacore::RunSimulationUntilTimeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aquacore::RunSimulationUntilTimeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aquacore::RunSimulationUntilTimeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aquacore::RunSimulationUntilTimeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e9b97c64adca29990ce6f7a0dc757a00";
  }

  static const char* value(const ::aquacore::RunSimulationUntilTimeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe9b97c64adca2999ULL;
  static const uint64_t static_value2 = 0x0ce6f7a0dc757a00ULL;
};

template<class ContainerAllocator>
struct DataType< ::aquacore::RunSimulationUntilTimeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aquacore/RunSimulationUntilTimeRequest";
  }

  static const char* value(const ::aquacore::RunSimulationUntilTimeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aquacore::RunSimulationUntilTimeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time desired_time\n\
";
  }

  static const char* value(const ::aquacore::RunSimulationUntilTimeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aquacore::RunSimulationUntilTimeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.desired_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RunSimulationUntilTimeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aquacore::RunSimulationUntilTimeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aquacore::RunSimulationUntilTimeRequest_<ContainerAllocator>& v)
  {
    s << indent << "desired_time: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.desired_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AQUACORE_MESSAGE_RUNSIMULATIONUNTILTIMEREQUEST_H
