// Generated by gencpp from file aquacore/SetLegParamsRequest.msg
// DO NOT EDIT!


#ifndef AQUACORE_MESSAGE_SETLEGPARAMSREQUEST_H
#define AQUACORE_MESSAGE_SETLEGPARAMSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aquacore
{
template <class ContainerAllocator>
struct SetLegParamsRequest_
{
  typedef SetLegParamsRequest_<ContainerAllocator> Type;

  SetLegParamsRequest_()
    : amplitude(0.0)
    , period(0.0)  {
    }
  SetLegParamsRequest_(const ContainerAllocator& _alloc)
    : amplitude(0.0)
    , period(0.0)  {
  (void)_alloc;
    }



   typedef float _amplitude_type;
  _amplitude_type amplitude;

   typedef float _period_type;
  _period_type period;




  typedef boost::shared_ptr< ::aquacore::SetLegParamsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aquacore::SetLegParamsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetLegParamsRequest_

typedef ::aquacore::SetLegParamsRequest_<std::allocator<void> > SetLegParamsRequest;

typedef boost::shared_ptr< ::aquacore::SetLegParamsRequest > SetLegParamsRequestPtr;
typedef boost::shared_ptr< ::aquacore::SetLegParamsRequest const> SetLegParamsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aquacore::SetLegParamsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aquacore::SetLegParamsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace aquacore

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'aquacore': ['/home/ran/Documents/Assignment1/src/aquacore/msg', '/home/ran/Documents/Assignment1/devel/share/aquacore/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::aquacore::SetLegParamsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aquacore::SetLegParamsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aquacore::SetLegParamsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aquacore::SetLegParamsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aquacore::SetLegParamsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aquacore::SetLegParamsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aquacore::SetLegParamsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1792bf569e4223f89286c37967c01dcf";
  }

  static const char* value(const ::aquacore::SetLegParamsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1792bf569e4223f8ULL;
  static const uint64_t static_value2 = 0x9286c37967c01dcfULL;
};

template<class ContainerAllocator>
struct DataType< ::aquacore::SetLegParamsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aquacore/SetLegParamsRequest";
  }

  static const char* value(const ::aquacore::SetLegParamsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aquacore::SetLegParamsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 amplitude\n\
float32 period\n\
";
  }

  static const char* value(const ::aquacore::SetLegParamsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aquacore::SetLegParamsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.amplitude);
      stream.next(m.period);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetLegParamsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aquacore::SetLegParamsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aquacore::SetLegParamsRequest_<ContainerAllocator>& v)
  {
    s << indent << "amplitude: ";
    Printer<float>::stream(s, indent + "  ", v.amplitude);
    s << indent << "period: ";
    Printer<float>::stream(s, indent + "  ", v.period);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AQUACORE_MESSAGE_SETLEGPARAMSREQUEST_H
