// Generated by gencpp from file aquacore/SetTargetAnglesRequest.msg
// DO NOT EDIT!


#ifndef AQUACORE_MESSAGE_SETTARGETANGLESREQUEST_H
#define AQUACORE_MESSAGE_SETTARGETANGLESREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aquacore
{
template <class ContainerAllocator>
struct SetTargetAnglesRequest_
{
  typedef SetTargetAnglesRequest_<ContainerAllocator> Type;

  SetTargetAnglesRequest_()
    : target_roll(0.0)
    , target_pitch(0.0)
    , target_yaw(0.0)  {
    }
  SetTargetAnglesRequest_(const ContainerAllocator& _alloc)
    : target_roll(0.0)
    , target_pitch(0.0)
    , target_yaw(0.0)  {
  (void)_alloc;
    }



   typedef float _target_roll_type;
  _target_roll_type target_roll;

   typedef float _target_pitch_type;
  _target_pitch_type target_pitch;

   typedef float _target_yaw_type;
  _target_yaw_type target_yaw;




  typedef boost::shared_ptr< ::aquacore::SetTargetAnglesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aquacore::SetTargetAnglesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetTargetAnglesRequest_

typedef ::aquacore::SetTargetAnglesRequest_<std::allocator<void> > SetTargetAnglesRequest;

typedef boost::shared_ptr< ::aquacore::SetTargetAnglesRequest > SetTargetAnglesRequestPtr;
typedef boost::shared_ptr< ::aquacore::SetTargetAnglesRequest const> SetTargetAnglesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aquacore::SetTargetAnglesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aquacore::SetTargetAnglesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace aquacore

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'aquacore': ['/home/ran/Documents/Assignment1/src/aquacore/msg', '/home/ran/Documents/Assignment1/devel/share/aquacore/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::aquacore::SetTargetAnglesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aquacore::SetTargetAnglesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aquacore::SetTargetAnglesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aquacore::SetTargetAnglesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aquacore::SetTargetAnglesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aquacore::SetTargetAnglesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aquacore::SetTargetAnglesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2fb51b5ca215261890b0dd7f7ef256d0";
  }

  static const char* value(const ::aquacore::SetTargetAnglesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2fb51b5ca2152618ULL;
  static const uint64_t static_value2 = 0x90b0dd7f7ef256d0ULL;
};

template<class ContainerAllocator>
struct DataType< ::aquacore::SetTargetAnglesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aquacore/SetTargetAnglesRequest";
  }

  static const char* value(const ::aquacore::SetTargetAnglesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aquacore::SetTargetAnglesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 target_roll\n\
float32 target_pitch\n\
float32 target_yaw\n\
";
  }

  static const char* value(const ::aquacore::SetTargetAnglesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aquacore::SetTargetAnglesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_roll);
      stream.next(m.target_pitch);
      stream.next(m.target_yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetTargetAnglesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aquacore::SetTargetAnglesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aquacore::SetTargetAnglesRequest_<ContainerAllocator>& v)
  {
    s << indent << "target_roll: ";
    Printer<float>::stream(s, indent + "  ", v.target_roll);
    s << indent << "target_pitch: ";
    Printer<float>::stream(s, indent + "  ", v.target_pitch);
    s << indent << "target_yaw: ";
    Printer<float>::stream(s, indent + "  ", v.target_yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AQUACORE_MESSAGE_SETTARGETANGLESREQUEST_H
