// Generated by gencpp from file aquacore/SetTargetDepthRequest.msg
// DO NOT EDIT!


#ifndef AQUACORE_MESSAGE_SETTARGETDEPTHREQUEST_H
#define AQUACORE_MESSAGE_SETTARGETDEPTHREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aquacore
{
template <class ContainerAllocator>
struct SetTargetDepthRequest_
{
  typedef SetTargetDepthRequest_<ContainerAllocator> Type;

  SetTargetDepthRequest_()
    : depth(0.0)  {
    }
  SetTargetDepthRequest_(const ContainerAllocator& _alloc)
    : depth(0.0)  {
  (void)_alloc;
    }



   typedef float _depth_type;
  _depth_type depth;




  typedef boost::shared_ptr< ::aquacore::SetTargetDepthRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aquacore::SetTargetDepthRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetTargetDepthRequest_

typedef ::aquacore::SetTargetDepthRequest_<std::allocator<void> > SetTargetDepthRequest;

typedef boost::shared_ptr< ::aquacore::SetTargetDepthRequest > SetTargetDepthRequestPtr;
typedef boost::shared_ptr< ::aquacore::SetTargetDepthRequest const> SetTargetDepthRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aquacore::SetTargetDepthRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aquacore::SetTargetDepthRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace aquacore

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'aquacore': ['/home/ran/Documents/Assignment1/src/aquacore/msg', '/home/ran/Documents/Assignment1/devel/share/aquacore/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::aquacore::SetTargetDepthRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aquacore::SetTargetDepthRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aquacore::SetTargetDepthRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aquacore::SetTargetDepthRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aquacore::SetTargetDepthRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aquacore::SetTargetDepthRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aquacore::SetTargetDepthRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6deb06b7b7183f5581b3362a0cb413b7";
  }

  static const char* value(const ::aquacore::SetTargetDepthRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6deb06b7b7183f55ULL;
  static const uint64_t static_value2 = 0x81b3362a0cb413b7ULL;
};

template<class ContainerAllocator>
struct DataType< ::aquacore::SetTargetDepthRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aquacore/SetTargetDepthRequest";
  }

  static const char* value(const ::aquacore::SetTargetDepthRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aquacore::SetTargetDepthRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 depth\n\
";
  }

  static const char* value(const ::aquacore::SetTargetDepthRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aquacore::SetTargetDepthRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.depth);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetTargetDepthRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aquacore::SetTargetDepthRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aquacore::SetTargetDepthRequest_<ContainerAllocator>& v)
  {
    s << indent << "depth: ";
    Printer<float>::stream(s, indent + "  ", v.depth);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AQUACORE_MESSAGE_SETTARGETDEPTHREQUEST_H
