// Generated by gencpp from file aquacore/SetUpRegulatedSwimModeRequest.msg
// DO NOT EDIT!


#ifndef AQUACORE_MESSAGE_SETUPREGULATEDSWIMMODEREQUEST_H
#define AQUACORE_MESSAGE_SETUPREGULATEDSWIMMODEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aquacore
{
template <class ContainerAllocator>
struct SetUpRegulatedSwimModeRequest_
{
  typedef SetUpRegulatedSwimModeRequest_<ContainerAllocator> Type;

  SetUpRegulatedSwimModeRequest_()
    : target_yaw(0.0)
    , target_depth(0.0)  {
    }
  SetUpRegulatedSwimModeRequest_(const ContainerAllocator& _alloc)
    : target_yaw(0.0)
    , target_depth(0.0)  {
  (void)_alloc;
    }



   typedef float _target_yaw_type;
  _target_yaw_type target_yaw;

   typedef float _target_depth_type;
  _target_depth_type target_depth;




  typedef boost::shared_ptr< ::aquacore::SetUpRegulatedSwimModeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aquacore::SetUpRegulatedSwimModeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetUpRegulatedSwimModeRequest_

typedef ::aquacore::SetUpRegulatedSwimModeRequest_<std::allocator<void> > SetUpRegulatedSwimModeRequest;

typedef boost::shared_ptr< ::aquacore::SetUpRegulatedSwimModeRequest > SetUpRegulatedSwimModeRequestPtr;
typedef boost::shared_ptr< ::aquacore::SetUpRegulatedSwimModeRequest const> SetUpRegulatedSwimModeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aquacore::SetUpRegulatedSwimModeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aquacore::SetUpRegulatedSwimModeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace aquacore

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'aquacore': ['/home/ran/Documents/Assignment1/src/aquacore/msg', '/home/ran/Documents/Assignment1/devel/share/aquacore/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::aquacore::SetUpRegulatedSwimModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aquacore::SetUpRegulatedSwimModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aquacore::SetUpRegulatedSwimModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aquacore::SetUpRegulatedSwimModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aquacore::SetUpRegulatedSwimModeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aquacore::SetUpRegulatedSwimModeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aquacore::SetUpRegulatedSwimModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0eb67c11df69dbb1cbae50ded84c7aa2";
  }

  static const char* value(const ::aquacore::SetUpRegulatedSwimModeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0eb67c11df69dbb1ULL;
  static const uint64_t static_value2 = 0xcbae50ded84c7aa2ULL;
};

template<class ContainerAllocator>
struct DataType< ::aquacore::SetUpRegulatedSwimModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aquacore/SetUpRegulatedSwimModeRequest";
  }

  static const char* value(const ::aquacore::SetUpRegulatedSwimModeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aquacore::SetUpRegulatedSwimModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 target_yaw\n\
float32 target_depth\n\
\n\
";
  }

  static const char* value(const ::aquacore::SetUpRegulatedSwimModeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aquacore::SetUpRegulatedSwimModeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_yaw);
      stream.next(m.target_depth);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetUpRegulatedSwimModeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aquacore::SetUpRegulatedSwimModeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aquacore::SetUpRegulatedSwimModeRequest_<ContainerAllocator>& v)
  {
    s << indent << "target_yaw: ";
    Printer<float>::stream(s, indent + "  ", v.target_yaw);
    s << indent << "target_depth: ";
    Printer<float>::stream(s, indent + "  ", v.target_depth);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AQUACORE_MESSAGE_SETUPREGULATEDSWIMMODEREQUEST_H
