// Generated by gencpp from file aquacore/StepSimulationRequest.msg
// DO NOT EDIT!


#ifndef AQUACORE_MESSAGE_STEPSIMULATIONREQUEST_H
#define AQUACORE_MESSAGE_STEPSIMULATIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aquacore
{
template <class ContainerAllocator>
struct StepSimulationRequest_
{
  typedef StepSimulationRequest_<ContainerAllocator> Type;

  StepSimulationRequest_()
    : duration(0.0)  {
    }
  StepSimulationRequest_(const ContainerAllocator& _alloc)
    : duration(0.0)  {
  (void)_alloc;
    }



   typedef double _duration_type;
  _duration_type duration;




  typedef boost::shared_ptr< ::aquacore::StepSimulationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aquacore::StepSimulationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StepSimulationRequest_

typedef ::aquacore::StepSimulationRequest_<std::allocator<void> > StepSimulationRequest;

typedef boost::shared_ptr< ::aquacore::StepSimulationRequest > StepSimulationRequestPtr;
typedef boost::shared_ptr< ::aquacore::StepSimulationRequest const> StepSimulationRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aquacore::StepSimulationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aquacore::StepSimulationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace aquacore

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'aquacore': ['/home/ran/Documents/Assignment1/src/aquacore/msg', '/home/ran/Documents/Assignment1/devel/share/aquacore/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::aquacore::StepSimulationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aquacore::StepSimulationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aquacore::StepSimulationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aquacore::StepSimulationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aquacore::StepSimulationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aquacore::StepSimulationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aquacore::StepSimulationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "efce4fd63555f8abdd034fb55c87e5aa";
  }

  static const char* value(const ::aquacore::StepSimulationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xefce4fd63555f8abULL;
  static const uint64_t static_value2 = 0xdd034fb55c87e5aaULL;
};

template<class ContainerAllocator>
struct DataType< ::aquacore::StepSimulationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aquacore/StepSimulationRequest";
  }

  static const char* value(const ::aquacore::StepSimulationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aquacore::StepSimulationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 duration\n\
";
  }

  static const char* value(const ::aquacore::StepSimulationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aquacore::StepSimulationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StepSimulationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aquacore::StepSimulationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aquacore::StepSimulationRequest_<ContainerAllocator>& v)
  {
    s << indent << "duration: ";
    Printer<double>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AQUACORE_MESSAGE_STEPSIMULATIONREQUEST_H
